M48
; DRILL file {KiCad 9.0.4-9.0.4-0~ubuntu22.04.1} date 2025-09-17T13:23:31-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-17T13:23:31-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4-9.0.4-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.500
%
G90
G05
T1
X102.61Y-87.33
X108.39Y-87.33
X122.11Y-87.33
X127.89Y-87.33
T2
X119.0Y-95.55
T3
X94.0Y-95.55
T4
X130.775Y-94.075
M30
